### ISSUE TITLE
Hex code needs updating

### ISSUE THREAD

**Issue by cfgreene** [coopdigital/coop-frontend#237]
The hex code for Link focus and Button focus is incorrect. It currently states #EB5F1E but this is the old orange color. It should be #8D44D8

![image (23)](https://user-images.githubusercontent.com/16582745/94803756-b1c5fe80-03e1-11eb-94ca-f0918466a6ef.png)

**Comment by colinrotherham** [comment]
Fixed in https://github.com/coopdigital/coop-frontend/pull/238
