### ISSUE TITLE
Making responsive images generic

### ISSUE THREAD

**Issue by jiebinsu** [coopdigital/coop-frontend#245]
Different classes are added onto figure and picture elements in different components that use responsive images.
e.g. signpost, membership banner, editorial card, feature card and product card.
Could we remove the classes and just wrap the figure in a div with the necessary styles and have figure and picture inherit global styles. These styles are duplicated across different components and the following will achieve the same effect:

i.e.
```
figure {
  margin: 0;
}

picture {
  display: block;
}
```

This way we can remove the unnecessary classes and make image generic so it can be easily substituted.
If there are any necessary styling changes that is required, it should be on a div wrapping the figure:

i.e.

use:
```
<div class="coop-c-editorialcard__inner">
  <div class="coop-c-editorialcard__media">
    <figure>
      <picture></picture>
    </figure>
  </div>
  <div class="coop-c-editorialcard__content"></div>
</div>
```

instead of:

```
<div class="coop-c-editorialcard__inner">
  <figure class="coop-c-editorialcard__media">
    <picture class="coop-c-editorialcard__image"></picture>
  </figure>
  <div class="coop-c-editorialcard__content"></div>
</div>
```

**Comment by matt-tyas** [comment]
Sent @colinrotherham a message internally about some work he's doing around this.

**Comment by omidantilong** [comment]
@matt-tyas can this be closed?

**Comment by omidantilong** [comment]
I'm going to close this for now.
