### ISSUE TITLE
Document testing guide using react testing library

### ISSUE THREAD

**Issue by dalecreativ** [coopdigital/coop-frontend#398]
- [ ] Document how to replace any enzyme and react-test-renderer tests with react-testing-library when moving components over to coop-frontend from coop-ds-storybook.
- [ ] Document replacing snapshot testing with react testing library tests to assert DOM outputs
- [ ] Document what tools we will use for testing moving forward

**Comment by omidantilong** [comment]
As far as i can tell, RTL is not being used for the components currently. We do have it working in the workbench now, with appropriate configs for babel/jest etc (and additional stuff for Next.js)

We should definitely look to pick this up again. Closing this issue for now though as it relates to storybook.
