### ISSUE TITLE
Remove package-level config files

### ISSUE THREAD

**Issue by froddd** [coopdigital/coop-frontend#41]
Newly added component packages all contain several package-level config files which should now be covered by the mono-repo ones:

```
.browserlistrc
.editorconfig
.gitattributes
.gitignore
.postcssrc
.stylelintrc
```

Each file should be inspected to make sure there aren't any package-specific rules that need retaining, or that provide a good default that could be moved to the root level.

**Comment by matt-tyas** [comment]
@froddd I'm not 100% sure there isn't a use case where you need them. I'll chat to you about it.

**Comment by matt-tyas** [comment]
@colinrotherham @froddd can I conform if this has now been done?

**Comment by colinrotherham** [comment]
We still have:

**.browserlistrc**
This might be safe to remove, just need to confirm if autoprefixer uses the top-level one instead.

**.editorconfig**
We can remove this one, editors and IDEs will always use the top-level one.

**.npmrc**
This was added recently (please keep) to prevent any package lock files being created.

I've got a super clean up PR open here, let me take a quick look https://github.com/coopdigital/coop-frontend/pull/197

**Comment by colinrotherham** [comment]
Wow, so the `.browserlistrc` files were entirely ignored.

It's supposed to be `.browserslistrc` (missing "s" typo) so we're shipping various unnecessary prefixes etc 🤦

**Comment by colinrotherham** [comment]
New versions were published following this change:

```
 - @coopdigital/component-card--product@2.1.17
 - @coopdigital/component-card@3.1.17
 - @coopdigital/component-date-input@1.0.11
 - @coopdigital/component-notification--alert@1.0.28
 - @coopdigital/component-notification@1.0.24
 - @coopdigital/component-search@2.1.17
 - @coopdigital/component-signpost@3.1.17
 - @coopdigital/component-skipnav@2.1.17
 - @coopdigital/component-squircles@2.1.17
 - @coopdigital/component-tags@3.1.17
 - @coopdigital/component-template@0.1.1
 - @coopdigital/css-foundations@5.2.2
 - @coopdigital/foundations-buttons@2.2.2
 - @coopdigital/foundations-colors@2.1.17
 - @coopdigital/foundations-forms@4.0.10
 - @coopdigital/foundations-global@3.1.16
 - @coopdigital/foundations-grid@2.0.8
 - @coopdigital/foundations-layout@3.2.2
 - @coopdigital/foundations-tables@2.1.16
 - @coopdigital/foundations-typography@4.1.16
 - @coopdigital/foundations-vars@3.2.2
 - @coopdigital/shared-component--app@1.0.6
 - @coopdigital/shared-component--editorialcard@2.1.17
 - @coopdigital/shared-component--featurecard@2.1.19
 - @coopdigital/shared-component--hero@2.1.17
 - @coopdigital/shared-component--image@2.1.17
 - @coopdigital/shared-component--linklist@2.1.19
 - @coopdigital/shared-component--membership@2.1.17
 - @coopdigital/shared-component--membershipfeatured@1.0.1
 - @coopdigital/shared-component--membershiphero@1.0.8
 - @coopdigital/shared-component--offers@2.1.17
 - @coopdigital/shared-component--offerspromo@1.0.6
 - @coopdigital/shared-component--postcode@2.1.18
 - @coopdigital/shared-component--signpost@2.1.17
 - @coopdigital/shared-component--signpostlist@1.0.4
 - @coopdigital/shared-component--statement@2.2.3
 - @coopdigital/shared-component--text@2.1.17
 - @coopdigital/shared-component--totaliser@1.0.7
 - @coopdigital/shared-component--video@2.1.17
```

A quick scan through the CSS shows that all `-o-` (Opera) prefixes have gone, probably more.
