### ISSUE TITLE
Unnecessary rules in new .coop-t-headline-mega class

### ISSUE THREAD

**Issue by matt-tyas** [coopdigital/coop-frontend#538]
In the following lines of the typography.pcss file we don't need text-transform: uppercase; set on the .coop-t-headline-mega class as this headline might sometimes appear lowercase. This was down to my bad instructions. If we want uppercase we should apply the modifier class .coop-t-headline-upper. 

The result can be seen on [this page](https://www.coop.co.uk/experience-library/examples/foundations/font-sizes.html) where the second Heading Mega is uppercase - it should be lowercase. 

There are before and after screenshots included.

![Screenshot 2024-09-03 at 16 33 34](https://github.com/user-attachments/assets/391b5f82-b853-402b-af6f-4558f779668d)
![Screenshot 2024-09-03 at 16 34 56](https://github.com/user-attachments/assets/0ef6c174-3303-428c-989e-8a451a3b8a71)

The lowercase variation should have a line height of 105% where as upper should always be 100%.

Current CSS:
```
.coop-t-headline-upper {
  font-family: var(--font-family-headline);
  text-transform: uppercase;
  line-height: 100%;
}

.coop-t-headline-mega {
  font-family: var(--font-family-headline);
  color: var(--color-brand-coop);
  text-transform: uppercase; 
  line-height: 100%;
  font-size: var(--type-headline-mega-xs);

  @media (--mq-small) {
    font-size: var(--type-headline-mega-s);
  }

  @media (--mq-medium) {
    font-size: var(--type-headline-mega-m);
  }
}
```

Suggested amends:
```
.coop-t-headline-upper {
// removed font family as this is specified on .coop-t-headline
  text-transform: uppercase;
  line-height: 100%;
}

.coop-t-headline-mega {
  // removed font family as this is specified on .coop-t-headline
  color: var(--color-brand-coop);
   // removed uppercase as this is specified on .coop-t-headline-upper
   // removed line-height as this is specified on .coop-t-headline-upper and .coop-t-headline
  font-size: var(--type-headline-mega-xs);

  @media (--mq-small) {
    font-size: var(--type-headline-mega-s);
  }

  @media (--mq-medium) {
    font-size: var(--type-headline-mega-m);
  }
}
```

**Comment by theodorekouzelis** [comment]
Fixed in https://github.com/coopdigital/coop-frontend/commit/cf74bf6962fe5d751de5e177f96ad5984652bfbc & https://github.com/coopdigital/coop-frontend/commit/c368c4b5785395321d6b1b254d74c5c7cf3f0d6a
