### ISSUE TITLE
Main body properties are set in global CSS instead of typography

### ISSUE THREAD

**Issue by froddd** [coopdigital/coop-frontend#56]
The foundations-global CSS package sets the font properties on the body. These should be set in the typography package, otherwise including global on its own would fail to find the correct font, etc:

https://github.com/coopdigital/coop-frontend/blob/master/packages/foundations-global/src/global.pcss#L11-L30

I'd suggest leaving `position`, `margin` and `padding` properties here but moving everything else.

**Comment by froddd** [comment]
[Testing webhook]

**Comment by omidantilong** [comment]
Closing as this was all migrated to the `foundations` repo.
